apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: web-canary
  namespace: web-canary
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: web
        image: fabricioveronez/web-color:green
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "200Mi"
            cpu: "250m"
          limits:
            memory: "500Mi"
            cpu: "500m"
  strategy:
    canary: 
      steps:
        - setWeight: 25
        - analysis:
            templates:
            - templateName: web-canary-analysis
        - setWeight: 50
        - analysis:
            templates:
            - templateName: web-canary-analysis
        - setWeight: 100
--- 
apiVersion: v1
kind: Service
metadata:
  name: web-canary
  namespace: web-canary
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
